[workspace]
root = "."
workspaces = [
  "packages/*",
  "apps/*"
]

[test]
root = "."
match = [
  "test/**/*.test.{ts,tsx}",
  "packages/*/src/**/*.test.{ts,tsx,mts,cts}",
  "apps/*/src/**/*.test.{ts,tsx}"
]
exclude = ["**/dist/**", "**/build/**", "**/__dist/**"]
